---
# Kubernetes version to install
k8s_version: "1.32"

# Containerd version (leave empty for latest from repo)
containerd_version: ""

# Control plane endpoint (nginx LB VIP)
control_plane_endpoint: "{{ lb_vip }}:6443"

# Pod network CIDR
pod_network_cidr: "10.244.0.0/16"

# Service CIDR
service_cidr: "10.96.0.0/12"

# Calico is the default CNI
cni_plugin: "calico"
