[lb]
worker3 ansible_host=192.168.4.172

[masters]
master1 ansible_host=192.168.4.168
master2 ansible_host=192.168.4.167
master3 ansible_host=192.168.4.171

[workers]
worker1 ansible_host=192.168.4.170
worker2 ansible_host=192.168.4.169
worker3 ansible_host=192.168.4.172

[k8s_cluster:children]
masters
workers

[k8s_cluster:vars]
ansible_user=ansible
ansible_ssh_pass=ansible
ansible_become=yes
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3
lb_vip=192.168.4.172
